### ISSUE TITLE
Update to latest version of Angular Material

### ISSUE THREAD

**Issue by IGx89** [Ashkettle/ashkettle-ngmaterial#3]
You're currently using version 0.6.0-rc3 and the latest is 0.7.0-rc1. Some of the examples, like https://material.angularjs.org/#/demo/material.components.sidenav, require at least 0.6.1 to work properly.

Thanks a lot for this module, btw! Awesome you putting this together :)

**Comment by Ashkettle** [comment]
I'll be updating it tomorrow utilizing the CDN to make it better.  I wanted
to do it earlier, but ran I wanted to run a few more tests before checking
it in.

I'll send you an email when it's all updated.

**Comment by Ashkettle** [comment]
Sorry that I didn't get back to you.  I sprained my back and have been out
being able to sit in front of a computer (which, since it's my career,
isn't great).  I felt good enough today to make a quick update to use the
CDN and point to 0.6.1, which is the current stable version.  I'll monitor
for when 0.7.1 goes stable and update.

I won't be able to thoroughly test it as well as I'd like, but it's up and
published.

**Comment by IGx89** [comment]
No problem! Real sorry to hear about your back :(. Thanks a lot!

**Comment by tgienger** [comment]
Where can I edit this to point to the version I want?

**Comment by Ashkettle** [comment]
I'll try to get it up to 0.7.1 in the next day or so.
